### ISSUE TITLE
FosOauthServerBundle differences

### ISSUE THREAD

**Issue by ikodev** [FriendsOfSymfony/oauth2-php#113]
Hi,
I would like to know if there are majors differences between this bundle and the FosOauthServerBundle ? I am on a project that use both bundles and currently I don't figure out why they have been implemented together.

Thank you for your help / advice :)

**Comment by rdavaillaud** [comment]
Hi, 

I think I'm not wrong if I say that FosOauthServerBundle is the bundle used to implement Oauth2-php  within symfony.

Oauth2-php is "just" a lib, which can be used outside of a Symfony project.

**Comment by GuilhemN** [comment]
@rdavaillaud is right :)
