### ISSUE TITLE
Tag 1.3.1

### ISSUE THREAD

**Issue by LoicLEMEUT** [FriendsOfSymfony/oauth2-php#122]
@GuilhemN, could you please tag 1.3.1 with the recent changes from #121 .

Resolves:
- Update OAuth2.php #121 

Thanks ! :)

**Comment by GuilhemN** [comment]
Sorry for the delay, it is now released.
Don't hesitate to ping me again if I don't answer after some time, I receive quite a lot of notifications and I sometimes miss some.
