### ISSUE TITLE
Release #75

### ISSUE THREAD

**Issue by cpjolly** [FriendsOfSymfony/oauth2-php#80]
Can we bump the version number to 1.1.2 to release the feature from #75 ?

**Comment by cpjolly** [comment]
Until someone bumps the version number, the feature from #75 will not be available to users of FOSOAuthServerBundle

**Comment by cpjolly** [comment]
Until someone bumps the version number, the feature from #75 will not be available to users of FOSOAuthServerBundle

**Comment by j0k3r** [comment]
https://github.com/FriendsOfSymfony/oauth2-php/releases/tag/1.2.0
