### ISSUE TITLE
is secure to send password as plain text to get the access token?

### ISSUE THREAD

**Issue by bitgandtter** [FriendsOfSymfony/oauth2-php#84]
i have been using the FOSOAuthBundle that use this library. On the call to grantAccessToken its required to send the user password as plain text. Is this secure? Why is this required?

**Comment by Spomky** [comment]
The RFC6749 does not require the use of plain text passwords, but client or user credentials.
For example, we can imagine the password are salted before they are sent to the server or they are one-time passwords.

This library only supports plaintext password and generally, the use of a such password is not safe.
But as we cannot yet implement alternatives, you can adapt you security policy to enhance the safety provided.
For example:
* Communication must be done in a secured way (use only secured TLS versions and secured algorithms on your server)
* Do not restrict the size of the passwords
* Do not restrict the characters used
* Use a real random password generator
* Verify the quality of the passwords
* Lifetime of passwords is limited (force passwords to be changed for clients and users)
* Protect your server against brute force
* And so on...

IMHO, this issue should be considered as a major one.

**Comment by bitgandtter** [comment]
I realize that the issue is in the bundle. The library only use the provided storage driver to validate users credentials. In the case of the bundle it use lets say the FOSUserBundle provider which require username and password as plain text. I manage to build a workaround on that with my own storage passing it in the bundle configuration. On the method to validate the credentials I just compare that the data coming from the database match the one sent on the request so in this scenario y send the password already hashed from the client side. 

Can this proposal be a real usable one?
